#' Import cGENIE .res Files into Data Frames Robustly
#'
#' Reads .res files generated by cGENIE and returns a tidy data frame.
#' Automatically detects the delimiter and column headers.
#'
#' @param var Character string; variable name to import.
#' @param experiment Character string; path to experiment directory.
#' @param model Character string; model type. Default "biogem".
#'
#' @importFrom stringr str_split str_trim
#' @importFrom readr read_lines read_table
#' @importFrom dplyr select where
#' @return Data frame with imported data. Columns full of NAs are removed.
#' @export
cGENIE.res.import <- function(var, experiment, model = "biogem") {

  # Validate model
  if (model != "biogem") stop("Currently only 'biogem' model is supported.")

  # Construct file path safely
  prefix <- "biogem_series_"
  suffix <- ".res"
  file_path <- file.path(experiment, model, paste0(prefix, var, suffix))
  if (!file.exists(file_path)) stop("File not found: ", file_path)

  # Read first few lines to detect delimiter and column names
  first_lines <- readr::read_lines(file_path, n_max = 5)
  delim <- if (any(grepl("/", first_lines))) "/" else "\\s+"
  header_line <- first_lines[1]

  # Extract column names
  col_names <- stringr::str_split(header_line, delim, simplify = TRUE) %>%
    stringr::str_trim()

  # Read data skipping header
  res_file <- readr::read_table(file_path, skip = 1, col_names = FALSE, show_col_types = FALSE)

  # Remove columns that are all NA
  res_file <- dplyr::select(res_file, dplyr::where(~ !all(is.na(.))))

  # Apply column names
  n_cols <- ncol(res_file)
  if (length(col_names) >= n_cols) {
    names(res_file) <- col_names[seq_len(n_cols)]
  } else {
    warning("Number of column names < number of data columns; using default names")
  }

  # Return as data.frame
  as.data.frame(res_file)
}
