#' Import cGENIE .res Files into Data Frames
#'
#' This function imports .res files generated by the cGENIE Earth system model and converts them into tidy data frames.
#'
#' @param var A character string specifying the variable name to import.
#' @param experiment A character string specifying the experiment directory containing the .res files.
#' @param model A character string specifying the model type. Default is "biogem".
#'
#' @return A data frame containing the imported data from the specified .res file, with columns named appropriately and any columns full of NAs removed.
#'
#' @details The function reads the .res file, removes columns that contain only NAs, and assigns appropriate column names based on the file's content.
#'
#'
#' @import readr
#' @import dplyr
#' @export

cGENIE.res.import <- function(var, experiment, model = "biogem") {
  # Load necessary libraries
  library(readr)
  library(dplyr)
  
  # Determine the file prefix based on the model type
  if (model == "biogem") {
    prefix <- "biogem_series_"
  }
  
  # Define the file suffix
  suffix <- ".res"
  
  # Construct the file path
  file_path <- paste0(experiment, "/", model, "/", prefix, var, suffix)
  
  # Import the results table from the .res file
  res_file <- read_table(file_path, show_col_types = FALSE)
  
  # Remove columns that contain only NAs
  res_file <- res_file %>% select_if(~ !any(is.na(.)))
  
  # Read the column names from the .res file
  # The column names have a different delimiter, so we read them separately
  res_file_names_frame <- read_delim(file_path, delim = "/", escape_double = FALSE, trim_ws = TRUE, show_col_types = FALSE)
  
  # Apply the column names obtained to the data columns in the results file
  names(res_file) <- names(res_file_names_frame)
  
  # Return the cleaned and properly named data frame
  return(res_file)
}
